IntalioTask/Models/ErrorViewModel.cs
using System;

namespace IntalioTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IntalioTask/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntalioTaskCore.Entities;
using IntalioTaskCore.IServices;
using Microsoft.AspNetCore.Mvc;

namespace IntalioTask.Controllers
{
    public class CountryController : Controller
    {
        //Country
        ICountryService _countryService;
        ICountryCurrencyRateService _countryCurrencyRateService;
        public CountryController(ICountryService countryService, ICountryCurrencyRateService countryRateService)
        {
            _countryService = countryService;
            _countryCurrencyRateService = countryRateService;
        }
        public ActionResult ViewPage()
        {
            ViewBag.countries = _countryService.GetAllCountry();
            return View();
        }
        [HttpGet]
        public JsonResult GetAllCountriesWithRate()
        {
            var result = _countryCurrencyRateService.GetAll();
            return Json(result);
        }
        public ActionResult ConfirmCountryCurrencyRate(countryCurrencyRate countryCurrenRate)
        {
            var result = _countryCurrencyRateService.ConfirmRate(countryCurrenRate);
            return RedirectToAction("ViewPage"); ;
        }
        
    }

}

IntalioTask/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using IntalioTask.Models;
using System.IO;

namespace IntalioTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int? id = null)
        {
            if (id.HasValue)
            {
                if (id == 1)
                {
                    throw new FileNotFoundException("File not found exception thrown in index.chtml");
                }
                else if (id == 2)
                {
                    return StatusCode(500);
                }
            }
            return View();
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IntalioTask/Views/Country/ViewPage.cshtml
@{
    Layout = null;
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css" />

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>
<link href="~/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/bootstrap.min.css" rel="stylesheet" />
<script src="~/js/bootstrap.js"></script>
<script src="~/js/bootstrap.min.js"></script>
@model IEnumerable<IntalioTaskCore.Entities.countryCurrencyRate>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Intalio Task</title>
    <script type="text/javascript" language="javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script>
        const getNewCases = async () => {
            const response = await fetch('/Country/GetAllCountriesWithRate');
            const data = await response.json();
            let usa = data;
            $('#loadingLabel').hide();
            $('#myTable').DataTable({
                data: usa,
                bLengthChange: false,
                columns: [
                    { data: 'countries.country_name', title: 'Country Name' }, 
                    { data: 'usdRate', title: 'USD Rate'},
                    { data: 'eurRate', title: 'EUR Rate' }
                                  
                ]
            });

        };
        getNewCases();
    </script>
    <style>
        #myTable_filter {
            float: left !important;
        }
    </style>
</head>
<body style="padding-top: 35px;padding-left: 18px;">
    <form method="post" asp-controller="Country" asp-action="ConfirmCountryCurrencyRate">
        <div class="row">
            <div class="col-md-5">
                <select id="ddlCountry" name="country_code" asp-items="@(new SelectList(ViewBag.countries,"country_code","country_name"))" class = "form-control borderDDL", data_live_search = "true">
                    <option value="0">Please select Country</option>
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
        <div class="row mt-5 ml-5" id="divData"></div>
    </form>
    <table id="myTable" class="table"></table>
    <div id="loadingLabel" >Loading...</div>
</body>
</html>

IntalioTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<br />

<div class="text-left">
    <p>
        <a href="/NoSuchPage">
            Request an endpoint that doesn't exist. Trigger a 404
        </a>.
    </p>
    <p><a href="/home/index/1">Trigger an exceptionn</a>.</p>
    <p><a href="/home/index/2">Return a 500 error.</a>.</p>
</div>

IntalioTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntalioTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntalioTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IntalioTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>